var greet = "Hello, ";
var place = "World";
console.log(greet.length);
console.log(greet.charAt(1));
console.log("Wo".concat("rl").concat("d!"));
console.log("ho-ho-ho".indexOf('h'));
console.log("ho-ho-ho".indexOf('o'));
console.log("ho-ho-ho".indexOf('-'));
console.log("ho-ho-ho".lastIndexOf('o'));
console.log("ho-ho-ho".split('-'));
console.log(greet.toUpperCase());
console.log(greet.toLowerCase());