// var test = typeof('What is this?');
// var test = typeof(10);
// var test = typeof(8.90);
// var test = typeof(true);
// var test = typeof(false);
// var test = typeof(1<2);
// var test = typeof([1,2,3]);
// var test = typeof({firstProprty: 1});
var test = typeof(function abc(){console.log('abc')});
console.log(test);